// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI_Phase1.Data;

#nullable disable

namespace ProductAPI_Phase1.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260323052729_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductAPI_Phase1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProdImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prod_Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products_tbl", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CostPrice = 950.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            Description = "High performance laptop with 16GB RAM and 512GB SSD",
                            Price = 1299.99m,
                            ProdImageUrl = "https://example.com/laptop.jpg",
                            Prod_Name = "Laptop Dell XPS 15",
                            ProductId = 12,
                            Stock = 25,
                            SupplierId = 101
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CostPrice = 60.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            Description = "Ergonomic wireless mouse with precision scrolling",
                            Price = 99.99m,
                            ProdImageUrl = "https://example.com/mouse.jpg",
                            Prod_Name = "Wireless Mouse Logitech MX Master 3",
                            ProductId = 15,
                            Stock = 150,
                            SupplierId = 102
                        },
                        new
                        {
                            Id = 3,
                            Category = "Furniture",
                            CostPrice = 890.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            Description = "Premium ergonomic office chair with lumbar support",
                            Price = 1495.00m,
                            ProdImageUrl = "https://example.com/chair.jpg",
                            Prod_Name = "Herman Miller Aeron Chair",
                            ProductId = 18,
                            Stock = 15,
                            SupplierId = 103
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
